### PR TITLE
Specific version of metanorma-cli (was getting build breaks with latest)

### PR DESCRIPTION
**Pull request by Kritner**
- https://github.com/celic/acvp-metanorma/actions/runs/149064012

### CODE REVIEW

**Comment by Kritner** [comment]
@ronaldtse tagging you for visibility.  Something *seems* to have changed in that we're getting build errors in GH actions today.  Tried with this branch to set the metanorma-cli version explicitly in the gem file, did not make a difference

**Comment by ronaldtse** [comment]
@Kritner will investigate. Maybe related to the newly released versions...? Ping @opoudjis.

**Comment by ronaldtse** [comment]
We are addressing this in https://github.com/metanorma/metanorma-ietf/issues/86 .

**Comment by ronaldtse** [comment]
metanorma/metanorma-ietf#86 has been fixed. This is probably not needed now. Thanks @Kritner !

**Pull request closed without merging**
