### PR TITLE
Remove `nits` extension that is no longer supported

### PR DESCRIPTION
**Pull request by ronaldtse**
This will unblock the make process. However, this issue (https://github.com/metanorma/metanorma-ietf/issues/86) still blocks proper deployment. It will be fixed soon.

Update: ~~metanorma/metanorma-ietf#86~~ is now fixed.

### CODE REVIEW

**Comment by ronaldtse** [comment]
Rebuilding metanorma-docker containers now.

**Comment by ronaldtse** [comment]
@celic @Kritner the latest docker containers work! Deployment will work once this is merged. Thanks for the patience!

**Comment by ronaldtse** [comment]
Ping @celic this is ready to be merged, this will fix the build.

**Comment by celic** [comment]
Thanks!

**Comment by ronaldtse** [comment]
Welcome!

**Comment by celic** [comment]
Fixed this without realizing there was a PR for it. Closing.

**Pull request closed without merging**
